-- ============================================
-- WinningBet — Add telegram_link_token to profiles
-- ============================================
-- One-time token used for the Telegram deep link (/start) flow.
-- Generated by the dashboard, consumed by telegram-webhook.js.
-- ============================================

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS telegram_link_token TEXT;

-- Index for token lookup (used by telegram-webhook.js)
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_telegram_link_token
    ON profiles(telegram_link_token)
    WHERE telegram_link_token IS NOT NULL;
